---
triple:          'arm64-apple-darwin'
binary-path:     app
relocations:
  - { offset: 0x19, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x1000039A0, symSize: 0x318 }
  - { offset: 0x293, size: 0x8, addend: 0x0, symName: _task7, symObjAddr: 0x428, symBinAddr: 0x100003DC8, symSize: 0xBC }
  - { offset: 0x32F, size: 0x8, addend: 0x0, symName: _swap, symObjAddr: 0x3E8, symBinAddr: 0x100003D88, symSize: 0x40 }
  - { offset: 0x377, size: 0x8, addend: 0x0, symName: _sort, symObjAddr: 0x318, symBinAddr: 0x100003CB8, symSize: 0xD0 }
  - { offset: 0x3F6, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x1000039A0, symSize: 0x318 }
...
