---
triple:          'arm64-apple-darwin'
binary-path:     app
relocations:
  - { offset: 0x19, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003BF0, symSize: 0x190 }
  - { offset: 0x299, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003BF0, symSize: 0x190 }
  - { offset: 0x362, size: 0x8, addend: 0x0, symName: _task18, symObjAddr: 0x0, symBinAddr: 0x100003D80, symSize: 0x128 }
  - { offset: 0x3D2, size: 0x8, addend: 0x0, symName: _task18, symObjAddr: 0x0, symBinAddr: 0x100003D80, symSize: 0x128 }
...
