---
triple:          'arm64-apple-darwin'
binary-path:     app
relocations:
  - { offset: 0x19, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003C70, symSize: 0x140 }
  - { offset: 0x2A0, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003C70, symSize: 0x140 }
  - { offset: 0x348, size: 0x8, addend: 0x0, symName: _task27, symObjAddr: 0x0, symBinAddr: 0x100003DB0, symSize: 0x120 }
  - { offset: 0x3BC, size: 0x8, addend: 0x0, symName: _task27, symObjAddr: 0x0, symBinAddr: 0x100003DB0, symSize: 0x120 }
...
