---
triple:          'arm64-apple-darwin'
binary-path:     app
relocations:
  - { offset: 0x19, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003A28, symSize: 0x1A8 }
  - { offset: 0x2A0, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003A28, symSize: 0x1A8 }
  - { offset: 0x378, size: 0x8, addend: 0x0, symName: _task14, symObjAddr: 0x0, symBinAddr: 0x100003BD0, symSize: 0x2C8 }
  - { offset: 0x3E8, size: 0x8, addend: 0x0, symName: _task14, symObjAddr: 0x0, symBinAddr: 0x100003BD0, symSize: 0x2C8 }
...
