---
triple:          'arm64-apple-darwin'
binary-path:     app
relocations:
  - { offset: 0x19, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003914, symSize: 0x2E0 }
  - { offset: 0x293, size: 0x8, addend: 0x0, symName: _mod, symObjAddr: 0x504, symBinAddr: 0x100003E18, symSize: 0x40 }
  - { offset: 0x2DF, size: 0x8, addend: 0x0, symName: _task6, symObjAddr: 0x3F0, symBinAddr: 0x100003D04, symSize: 0x114 }
  - { offset: 0x37B, size: 0x8, addend: 0x0, symName: _swap, symObjAddr: 0x3B0, symBinAddr: 0x100003CC4, symSize: 0x40 }
  - { offset: 0x3C3, size: 0x8, addend: 0x0, symName: _sort, symObjAddr: 0x2E0, symBinAddr: 0x100003BF4, symSize: 0xD0 }
  - { offset: 0x442, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003914, symSize: 0x2E0 }
...
