---
triple:          'arm64-apple-darwin'
binary-path:     app
relocations:
  - { offset: 0x19, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003C00, symSize: 0x1BC }
  - { offset: 0x299, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003C00, symSize: 0x1BC }
  - { offset: 0x35F, size: 0x8, addend: 0x0, symName: _task17, symObjAddr: 0x0, symBinAddr: 0x100003DBC, symSize: 0xDC }
  - { offset: 0x3D3, size: 0x8, addend: 0x0, symName: _task17, symObjAddr: 0x0, symBinAddr: 0x100003DBC, symSize: 0xDC }
...
