---
triple:          'arm64-apple-darwin'
binary-path:     app
relocations:
  - { offset: 0x19, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003AB8, symSize: 0x1C4 }
  - { offset: 0x299, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003AB8, symSize: 0x1C4 }
  - { offset: 0x380, size: 0x8, addend: 0x0, symName: _task11, symObjAddr: 0x0, symBinAddr: 0x100003C7C, symSize: 0x168 }
  - { offset: 0x3F4, size: 0x8, addend: 0x0, symName: _nod, symObjAddr: 0x168, symBinAddr: 0x100003DE4, symSize: 0x70 }
  - { offset: 0x42D, size: 0x8, addend: 0x0, symName: _task11, symObjAddr: 0x0, symBinAddr: 0x100003C7C, symSize: 0x168 }
...
