---
triple:          'arm64-apple-darwin'
binary-path:     app
relocations:
  - { offset: 0x19, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003798, symSize: 0x364 }
  - { offset: 0x29B, size: 0x8, addend: 0x0, symName: _print, symObjAddr: 0x568, symBinAddr: 0x100003D00, symSize: 0xFC }
  - { offset: 0x32F, size: 0x8, addend: 0x0, symName: _fun, symObjAddr: 0x40C, symBinAddr: 0x100003BA4, symSize: 0x15C }
  - { offset: 0x3DC, size: 0x8, addend: 0x0, symName: _cmp, symObjAddr: 0x364, symBinAddr: 0x100003AFC, symSize: 0xA8 }
  - { offset: 0x437, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003798, symSize: 0x364 }
...
