---
triple:          'arm64-apple-darwin'
binary-path:     app
relocations:
  - { offset: 0x19, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003BA0, symSize: 0x1A8 }
  - { offset: 0x299, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003BA0, symSize: 0x1A8 }
  - { offset: 0x362, size: 0x8, addend: 0x0, symName: _task22, symObjAddr: 0x0, symBinAddr: 0x100003D48, symSize: 0xB0 }
  - { offset: 0x3D2, size: 0x8, addend: 0x0, symName: _swap, symObjAddr: 0xB0, symBinAddr: 0x100003DF8, symSize: 0x78 }
  - { offset: 0x420, size: 0x8, addend: 0x0, symName: _task22, symObjAddr: 0x0, symBinAddr: 0x100003D48, symSize: 0xB0 }
...
