---
triple:          'arm64-apple-darwin'
binary-path:     app
relocations:
  - { offset: 0x19, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003B2C, symSize: 0x1D8 }
  - { offset: 0x90D, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003B2C, symSize: 0x1D8 }
  - { offset: 0x9F4, size: 0x8, addend: 0x0, symName: __Z5task8Pii, symObjAddr: 0x0, symBinAddr: 0x100003D04, symSize: 0xE8 }
  - { offset: 0x1047, size: 0x8, addend: 0x0, symName: __Z5sdvigPii, symObjAddr: 0xE8, symBinAddr: 0x100003DEC, symSize: 0x5C }
  - { offset: 0x109D, size: 0x8, addend: 0x0, symName: __Z5task8Pii, symObjAddr: 0x0, symBinAddr: 0x100003D04, symSize: 0xE8 }
...
