---
triple:          'arm64-apple-darwin'
binary-path:     app
relocations:
  - { offset: 0x19, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003980, symSize: 0x31C }
  - { offset: 0x28F, size: 0x8, addend: 0x0, symName: _swap, symObjAddr: 0x4C4, symBinAddr: 0x100003E44, symSize: 0x40 }
  - { offset: 0x2E1, size: 0x8, addend: 0x0, symName: _task4, symObjAddr: 0x3E8, symBinAddr: 0x100003D68, symSize: 0xDC }
  - { offset: 0x377, size: 0x8, addend: 0x0, symName: _sort, symObjAddr: 0x31C, symBinAddr: 0x100003C9C, symSize: 0xCC }
  - { offset: 0x3F6, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003980, symSize: 0x31C }
...
